# Generated by Django 6.0.5 on 2026-05-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_text', models.TextField()),
                ('scripture_reference', models.CharField(max_length=100)),
                ('video_url', models.URLField(blank=True, help_text="YouTube embed URL for 'Cultivate a rhythm' section", null=True)),
                ('date', models.DateField(unique=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('verse', 'Daily Verse'), ('news', 'Gospel News'), ('testimony', 'Testimony'), ('announcement', 'Announcement')], default='news', max_length=20)),
                ('content', models.TextField()),
                ('scripture_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo embed URL', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', '👍'), ('amen', '🙏'), ('fire', '🔥'), ('heart', '❤️'), ('praise', '🙌')], default='like', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
